using System.Globalization;using System.Windows;using System.Windows.Controls;using TapoCtrl.Models;using TapoCtrl.Services;
namespace TapoCtrl.Windows;
public partial class SettingsWindow:Window
{
 private readonly AppSettings _settings;private readonly SettingsService _service;private readonly bool _ja=CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ja",StringComparison.OrdinalIgnoreCase);
 public SettingsWindow(AppSettings settings,SettingsService service){InitializeComponent();_settings=settings;_service=service;var c=service.LoadSecret();UserBox.Text=c.User;PassBox.Password=c.Pass;HubBox.Text=string.Join(", ",settings.HubIps);PythonBox.Text=settings.PythonPath;LoggingBox.IsChecked=settings.LoggingEnabled;EntryBox.IsChecked=settings.VerboseFunctionEntryLogging;StaleBox.Text=settings.StaleDeviceMinutes.ToString();foreach(ComboBoxItem i in LevelBox.Items)if((string)i.Content==settings.LogLevel)LevelBox.SelectedItem=i;LevelBox.SelectedIndex=LevelBox.SelectedIndex<0?2:LevelBox.SelectedIndex;ApplyLanguage();}
 private void ApplyLanguage(){LogPathText.Text=(_ja?"ログ保存先: ":"Log folder: ")+System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"TapoCtrl","logs");InfoText.Text=_ja?"ログは日単位で作成し、7日を超えたファイルを週次ZIPへ自動アーカイブします。Traceは大量出力になるため、調査時だけ使用してください。":"Logs are created daily. Files older than seven days are automatically archived into weekly ZIP files. Use Trace only for troubleshooting because it produces high-volume output.";if(!_ja)return;Title="TapoCtrl 設定";PassLabel.Text="パスワード";HubLabel.Text="HUB IP（カンマ区切り）";PythonLabel.Text="Python 実行ファイル";LoggingBox.Content="ログ出力を有効にする";LevelLabel.Text="ログレベル";EntryBox.Content="関数入口の詳細ログを出力する";StaleLabel.Text="未取得時の再設定（分）";CancelButton.Content="キャンセル";SaveButton.Content="保存";}
 private void SaveClick(object s,RoutedEventArgs e){_settings.HubIps=HubBox.Text.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).ToList();_settings.PythonPath=string.IsNullOrWhiteSpace(PythonBox.Text)?"python":PythonBox.Text.Trim();_settings.LoggingEnabled=LoggingBox.IsChecked==true;_settings.VerboseFunctionEntryLogging=EntryBox.IsChecked==true;_settings.LogLevel=(LevelBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Information";if(int.TryParse(StaleBox.Text,out var m))_settings.StaleDeviceMinutes=Math.Clamp(m,1,60);_service.SaveSecret(UserBox.Text.Trim(),PassBox.Password);_service.Save(_settings);AppLog.Configure(_settings.LoggingEnabled,_settings.LogLevel,_settings.VerboseFunctionEntryLogging);DialogResult=true;}
}
